pthread.o: pthread.cc \
 /home/ugb/quinn.bischoff/kos/src/ulib/../testoptions.h \
 /home/ugb/quinn.bischoff/kos/src/ulib/../include/syscalls.h \
 /home/ugb/quinn.bischoff/kos/src/ulib/../include/kostypes.h \
 /home/ugb/quinn.bischoff/kos/src/ulib/../include/pthread.h \
 /home/ugb/quinn.bischoff/kos/src/ulib/../include/syscalls.h
libKOS.o: libKOS.cc \
 /home/ugb/quinn.bischoff/kos/src/ulib/../testoptions.h \
 /home/ugb/quinn.bischoff/kos/src/ulib/../include/syscalls.h \
 /home/ugb/quinn.bischoff/kos/src/ulib/../include/kostypes.h
